# @package _group_
env: 
  name: "cube_in_hand"
  class: "envs.cube_in_hand_env.CubeInHandEnv"
  params: 
    model_path: ${hydra:runtime.cwd}/envs/hand_v4/hand_v4_with_cube.xml
    control_dt: 0.01
    sim_decimation: 4
    action_scale: 0.15
    soft_joint_limit_factor: 0.9
    success_tolerance: 0.3
    frame_stack: 2
    max_episode_steps: 1000
    random: ${seed}
    task_kwargs:
      perturb_spec:
        mode: "range"
        params:
          object_mass: {min: 0.7, max: 1.3}
          object_inertia: {min: 0.7, max: 1.3}
          cube_friction: {min: 0.8, max: 1.2}
          fingertip_friction: {min: 0.6, max: 1.4}
          actuator_kp: {min: 0.8, max: 1.2}
          actuator_kv: {min: 0.8, max: 1.2}
          contact_damping: {min: 0.7, max: 1.3}
          gravity_scale: {min: 0.95, max: 1.05}

max_episode_steps: 1000

# training params 
num_random_steps: 5e3
num_train_steps: 1e6
eval_frequency: 1e4
num_eval_episodes: 10

# algorithm params
sac_critic_lr: 1e-4
sac_actor_lr: 1e-4
sac_alpha_lr: 1e-4

# replay buffer
replay_buffer_capacity: ${num_train_steps}

